# Use a imagem oficial do Node.js 20
FROM node:20-alpine

WORKDIR /app

# Copie os arquivos do projeto para o contêiner
COPY package.json yarn.lock /webhook/
COPY src/* /webhook/src/

# Instale as dependências
RUN yarn install --production

COPY . /app/

# Compile o código TypeScript
RUN yarn build

# Expõe a porta 3000
EXPOSE 3000

# Comando para iniciar o servidor
CMD ["yarn", "start"]
