version: '3'

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
